---
program: wandb-agent.py
project: qwop
method: grid
metric:
  name: rollout/ep_rew_mean
  goal: maximize
parameters:
  action: { value: train_dqn }
  c:
    parameters:
      out_dir_template: { value: "data/DQN-{run_id}" }
      log_tensorboard: { value: true }
      total_timesteps: { value: 10000 }
      max_episode_steps: { value: 5000 }
      n_checkpoints: { value: 5 }
      learner_kwargs:
        parameters:
          policy: { value: "MlpPolicy" }
          buffer_size: { value: 1000 }
          learning_starts: { value: 100 }
          batch_size: { value: 64 }
          tau: { value: 1.0 }
          gamma: { value: 0.995 }
          train_freq: { value: 4 }
          gradient_steps: { value: 1 }
          target_update_interval: { value: 2000 }
          exploration_fraction: { value: 0.01 }
          exploration_initial_eps: { value: 1 }
          exploration_final_eps: { value: 0.01 }
      learner_lr_schedule:
        parameters:
          fn: { value: "const" }
          initial_value: { value: 0.001 }
          step: { value: 0.75 }
          decays: { value: 15 }
          min_value: { value: 0.00001 }
      env_kwargs:
        parameters:
          driver: { value: "/Users/simo/Projects/qwop/vendor/chromedriver" }
          browser: { value: "/Applications/Brave Browser.app/Contents/MacOS/Brave Browser" }
          render_mode: { value: "browser" }
          failure_cost: { value: 10 }
          success_reward: { value: 50 }
          time_cost_mult: { value: 10 }
          frames_per_step: { value: 1 }
          stat_in_browser: { value: false }
          game_in_browser: { value: false }
          text_in_browser: { value: ~ }
          reload_on_reset: { value: false }
          auto_draw: { value: false }
          browser_mock: { value: false }
          r_for_terminate: { value: false }
          text_in_browser: { value: "Training in progress..." }
