---
# [int] Frames per second (use 30 for a genuine QWOP experience)
fps: 30

# [int] End-game screen duration in seconds
reset_delay: 1

# Env parameters
# The special "__include__" key allows to load them from another file.
# Keys listed here take precedence over keys loaded with __include__.
# See notes in `env.yml` for more info
env_kwargs:
  __include__: "config/env.yml"
  render_mode: "rgb_array"
  r_for_terminate: true
  stat_in_browser: true
  game_in_browser: false
  text_in_browser: "You are playing (press Escape to exit)"

# List of gym wrappers to use for the env
# Each list element must be a dict with "module", "cls" and "kwargs" keys
env_wrappers:
  # VerboseWrapper prints action and some game stats on each step
  - module: "src.env.v1.util.verbose_wrapper"
    cls: "VerboseWrapper"

  # RecordWrapper records episodes to a file
  - module: "tools.common"
    cls: "RecordWrapper"
    kwargs:
      # [string] Path to the file to store recorded episodes.
      rec_file: "data/recordings/recording-1.rec"

      # [bool] Overwrite out_file if already exists
      overwrite: true

      # [int] (optional) Discard episode if time > `max_time`
      max_time: 10

      # [int] (optional) Discard episode if distance < `min_distance`
      min_distance: 3

      # [bool] (optional) Discard episode if incomplete (eg. terminated via "R")
      complete_only: true
