---
# [int] Frames per second (use 30 for a genuine QWOP experience)
fps: 30

# [int] End-game screen duration in seconds
reset_delay: 1

# [List<string>] List of paths for the recordings to train with
# Glob patterns are supported, eg. "data/recordings/*.rec"
recordings:
  - "data/recordings/*.rec"

# Env parameters
# The special "__include__" key allows to load them from another file.
# Keys listed here take precedence over keys loaded with __include__.
# See notes in `env.yml` for more info
env_kwargs:
  __include__: "config/env.yml"
  auto_draw: true
  stat_in_browser: true
  game_in_browser: true
  text_in_browser: "Re-playing a previously recorded game"

# List of gym wrappers to use for the env
# Each list element must be a dict with "module" and "cls" keys
env_wrappers:
  # The Verbose wrapper prints the action along with some stats on each step
  - module: "src.env.v1.util.verbose_wrapper"
    cls: "VerboseWrapper"
