---
fps: 30
reset_delay: 1
recordings:
  # glob patterns are also allowed
  - "data/recordings/*.rec"
env_kwargs:
  __include__: "config/env.yml"
  auto_draw: true
  stat_in_browser: true
  game_in_browser: true
  text_in_browser: "Re-playing a previously recorded game"
env_wrappers:
  - module: "src.env.v1.util.verbose_wrapper"
    cls: "VerboseWrapper"
